channels:
- defaults
- pytorch
dependencies:
- python=3.6.6
- pytorch==1.4.0
- torchvision==0.5.0
- cudatoolkit=10.1
- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/19950822
  - azureml-defaults==0.1.0.19950822
  - azureml-pipeline-wrapper==0.1.0.19950822
  - scikit-learn==0.23.1
  - tqdm
  - pyarrow
name: project_environment